In [1]:
a = 10
b = 100000000000000000000000000000000000000000

print(a)
print(b)

10
100000000000000000000000000000000000000000


In [2]:
print(0.1 + 0.2) # 0.30000000000000004

0.30000000000000004


In [3]:
c = 3 + 4j

print(c.real) # 실수부 3.0
print(c.imag) # 허수부 4.0

3.0
4.0


In [5]:
# decimal 모듈안에 Decimal함수를 메모리에 로드
# 파이썬 언어가 제공하는 객체중 내장객체가 아닌것들은 import 후 사용
from decimal import Decimal

a = Decimal("0.1") # 인자값을 float으로 전달하면 전달하는 순간 오차가 발생하니 문자열로 입력한다.
b = Decimal("0.2")

print(a + b)

0.3


In [8]:
print(0.1 + 0.2 == 0.3) # False

print(Decimal("0.1") + Decimal("0.2") == Decimal("0.3")) # True

False
True


In [7]:
from fractions import Fraction

f = Fraction(1, 3)

print(f)

# 분수계산의 예
a = Fraction(1, 3)
b = Fraction(1, 6)
c = a + b
print(c)

d = a*b
print(d)

# 분수를 실수로 변환
print(float(c))
print(float(d))

1/3
1/2
1/18
0.5
0.05555555555555555


In [9]:
a = -1
b = 0
c = 1
d = 2
e = 0.1

print(bool(a)) # True
print(bool(b)) # False
print(bool(c)) # True
print(bool(d)) # True
print(bool(e)) # True

True
False
True
True
True


In [10]:
n = 10
print(n.bit_length()) # 10의 이진수 값(1010)의 길이

# bin()함수는 인자로 입력된 10진수의 2진수 문자열을 반환한다.
# 이진수 문자열 앞에 binary를 뜻하는 "0b"접두사를 앞에 붙여서 반환한다.
print(bin(n)) #0b1010 "0b" + "1010"

# bit_length()메서드는 n이라는 숫자 객체를 만들어야 존재하는 것이고,
# bin() 함수는 n객체와 상관없는 독립된 함수 객체이다.

print(bin(9)) # n과 상관없이 독립적으로 사용가능

4
0b1010
0b1001


In [11]:
print(pow(2, 3)) # 거듭제곱 int로 반환
print(divmod(10, 3)) # 몫과 나머지를 tuple로 반환
print(round(3.14159, 2)) # 반올림된 실수값을 반환
print(abs(-10)) # 절대값을 반환(반환 타입은 인자값과 같은 타입)

8
(3, 1)
3.14
10


In [12]:
pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ------------- -------------------------- 4.2/12.4 MB 41.1 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 33.7 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
print(a)

b = np.array([[5, 6],
              [7, 8]])
print(a + b) 
# [1+5  2+6] 
# [3+7  4+8]


c = np.array([[5, 6],
              [7, 8]])
d = np.array([[1, 2],
              [3, 4]])
print(c - d)


e = np.array([[1, 2],
              [3, 4]])
print(e * 10)


# 행렬 곱(Matrix Multiplication) 
#- 앞 행렬의 열의 수와 뒤 행렬의 행의 수가 같아야
#- 결과 행은 앞 행렬의 (행의 수 x 뒤 행렬의 열의 수)를 가지는 행렬이 된다.
#- 2행3열 @ 3행1열 --> "2행1열"의 결과 행렬이 반환 된다. 
#- 여기서 중요한 건 행렬곱연산은 행렬의 사이즈를 줄일 수 있다는 것이다. 
#- 데이터 과학에선 입력값의 특성(피처, 변수)이 너무 많을때 압축할때 행렬곱연산을 사용한다.  


import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # 2행3열

b = np.array([[10],
              [20],
              [30]])        # 3행1열

print(a @ b) # 결과는 2행1열
# [1×10 + 2×20 + 3×30]
# [4×10 + 5×20 + 6×30]

# 전치행렬
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.T)

[[1 2]
 [3 4]]
[[ 6  8]
 [10 12]]
[[4 4]
 [4 4]]
[[10 20]
 [30 40]]
[[140]
 [320]]
[[1 4]
 [2 5]
 [3 6]]


In [18]:
[[1, 2],[3, 4]]+[[5, 6],[7, 8]]


[[1, 2], [3, 4], [5, 6], [7, 8]]

In [ ]:
a = np,array([[1, 2, 3], 
              [4, 5, 6]])   #2행 3열

a = np,array([[]])


In [19]:
import numpy as np

# 2행 3열 행렬
W = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 3차원 벡터
x = np.array([10, 20, 30]) # 3열
print("행렬곱 전 차원 : ", x.shape)

# 행렬 곱
y = W @ x

print(y) # 2열로 변경 됨 -> 차원축소
print("행렬곱 후 차원 : ", y.shape)

행렬곱 전 차원 :  (3,)
[140 320]
행렬곱 후 차원 :  (2,)


In [23]:
a = [1, 2, 3]
b = [4, 5]
result = a + b
print(result) # [1, 2, 3, 4, 5]
print(a)
print(b)

a = a + b
print(a)

c = "py"
c = c +"thon"
print(c)

[1, 2, 3, 4, 5]
[1, 2, 3]
[4, 5]
[1, 2, 3, 4, 5]
python


In [24]:
nums = [10, 20]
result = nums * 3
print(result) # [10, 20, 10, 20, 10, 20]


# [30, 60] NumPy라이브러리로 행렬객체를 만들어 사용

[10, 20, 10, 20, 10, 20]


In [22]:
fruits = ["apple", "banana", "orange"]
print("banana" in fruits)

print("grape" in fruits)
print("grape" not in fruits)

True
False
True


In [ ]:
nums = [10, 20, 30, 40]

print(nums[0])
print(nums[-1])

# 인덱스 할당 연산
nums[2] = 99 # 리스트는 가변 객체
print(nums)

n2 = (3, 5)
print(n2[0])
n2[0] = 999 #does not support item assignment

10
40
[10, 20, 99, 40]
3


TypeError: 'tuple' object does not support item assignment

In [29]:
nums = [10, 20, 30, 40, 50]

print(nums[1:4]) # [20, 30, 40]
print(nums[:3]) # [10, 20, 30]
print(nums[2:]) # [30, 40, 50]
print(nums) #  [10, 20, 30, 40, 50] 슬라이싱 연산 후에도 리스트 자신은 변경되지 않는다. 

[20, 30, 40]
[10, 20, 30]
[30, 40, 50]
[10, 20, 30, 40, 50]


In [28]:
# 2칸씩 건너뛰기
nums = [10, 20, 30, 40, 50, 60, 70, 80]
print(nums[::2])

nums = [10, 20, 30, 40, 50, 60, 70, 80]
print(nums[1::2])


[10, 30, 50, 70]
[20, 40, 60, 80]


In [30]:
# 역순 출력
nums = [10, 20, 30, 40, 50]
print(nums[::-1]) # [50, 40, 30, 20, 10]

[50, 40, 30, 20, 10]


In [31]:
# 뒤에서 3개 추출
nums = [10, 20, 30, 40, 50, 60]
print(nums[-3:])

[40, 50, 60]


In [32]:
# 뒤에서 4개 중 2칸씩
nums = [10, 20, 30, 40, 50, 60, 70, 80]
print(nums[-4::2])

[50, 70]


In [33]:
# 뒤에서 앞으로 2칸씩
nums = [10, 20, 30, 40, 50, 60, 70, 80]
print(nums[::-2])

[80, 60, 40, 20]


In [34]:
# [5]위치부터 뒤로(-1) [1]위치 전까지
nums = [10, 20, 30, 40, 50, 60, 70]
print(nums[5:1:-1]) # 5위치부터 1전까지 -1칸식  [60, 50, 40, 30]

[60, 50, 40, 30]


In [35]:
# 마지막 5개를 역순으로
nums = [10, 20, 30, 40, 50, 60, 70, 80]
print(nums[-1:-6:-1])

[80, 70, 60, 50, 40]


In [36]:
# 슬라이싱 할당(슬라이싱 구간에 대입문)
nums = [10, 20, 30, 40, 50]
nums[1:4] = [7, 8] # 1~3구간 [20, 30, 40]에 [7, 8]을 대입 
print(nums) # [10, 7, 8, 50]

[10, 7, 8, 50]


In [37]:
# 슬라이싱 결과를 다른 변수에 대입
a = [10, 20, 30, 40, 50, 60]
b = a[:]
c = a[::-1]
d = a[1::2]
e = a[:2]

print(b)
print(c)
print(d)
print(e)

[10, 20, 30, 40, 50, 60]
[60, 50, 40, 30, 20, 10]
[20, 40, 60]
[10, 20]


In [38]:
nums = [10, 20, 30, 40, 50]

print(nums[1:4]) # [20, 30, 40]
print(nums[:3]) # [10, 20, 30]
print(nums[2:]) # [30, 40, 50]
print(nums) #  [10, 20, 30, 40, 50] 슬라이싱 연산 후에도 리스트 자신은 변경되지 않는다. 

# 2칸씩 건너뛰기
nums = [10, 20, 30, 40, 50, 60, 70, 80]
print(nums[::2])

nums = [10, 20, 30, 40, 50, 60, 70, 80]
print(nums[1::2])

# 역순 출력
nums = [10, 20, 30, 40, 50]
print(nums[::-1]) # [50, 40, 30, 20, 10]

# 뒤에서 3개 추출
nums = [10, 20, 30, 40, 50, 60]
print(nums[-3:])

# 뒤에서 4개 중 2칸씩
nums = [10, 20, 30, 40, 50, 60, 70, 80]
print(nums[-4::2])

# 뒤에서 앞으로 2칸씩
nums = [10, 20, 30, 40, 50, 60, 70, 80]
print(nums[::-2])

# [5]위치부터 뒤로(-1) [1]위치 전까지
nums = [10, 20, 30, 40, 50, 60, 70]
print(nums[5:1:-1]) # 5위치부터 1전까지 -1칸식  [60, 50, 40, 30]

# 마지막 5개를 역순으로
nums = [10, 20, 30, 40, 50, 60, 70, 80]
print(nums[-1:-6:-1])

# 슬라이싱 할당(슬라이싱 구간에 대입문)
nums = [10, 20, 30, 40, 50]
nums[1:4] = [7, 8] # 1~3구간 [20, 30, 40]에 [7, 8]을 대입 
print(nums) # [10, 7, 8, 50]

# 슬라이싱 결과를 다른 변수에 대입
a = [10, 20, 30, 40, 50, 60]
b = a[:]
c = a[::-1]
d = a[1::2]
e = a[:2]

print(b)
print(c)
print(d)
print(e)

[20, 30, 40]
[10, 20, 30]
[30, 40, 50]
[10, 20, 30, 40, 50]
[10, 30, 50, 70]
[20, 40, 60, 80]
[50, 40, 30, 20, 10]
[40, 50, 60]
[50, 70]
[80, 60, 40, 20]
[60, 50, 40, 30]
[80, 70, 60, 50, 40]
[10, 7, 8, 50]
[10, 20, 30, 40, 50, 60]
[60, 50, 40, 30, 20, 10]
[20, 40, 60]
[10, 20]


In [39]:
a = [10, 20, 30]
b = a

print(a)
print(b)
print(a == b)
print(a is b)

b[0] = 999
print(a) 
print(b) 

[10, 20, 30]
[10, 20, 30]
True
True
[999, 20, 30]
[999, 20, 30]


In [40]:
a = [10, 20, 30]
b = a[:]

print(a)
print(b)
print(a == b) 
print(a is b)

b[0] = 999
print(a) # [10, 20, 30]
print(b) # [999, 20, 30]

[10, 20, 30]
[10, 20, 30]
True
False
[10, 20, 30]
[999, 20, 30]


In [41]:
a = [1, 2, 3]
b = [1, 2, 3]
c = [1, 2, 4]

print(a == b) # True
print(a == c) # False

True
False


In [42]:
nums = [10, 20, 30, 40]

print(len(nums))
nums = [10, 20, 30, 40]

print(max(nums))
print(min(nums))
print(sum(nums))

4
40
10
100


In [43]:
# append() : 맨 뒤에 1개 추가
fruits = ["apple", "banana"]
fruits.append("orange")
print(fruits)

['apple', 'banana', 'orange']


In [44]:
# insert() : 원하는 위치에 추가
fruits = ["apple", "banana"]
fruits.insert(1, "orange")
print(fruits)

['apple', 'orange', 'banana']


In [45]:
# extend() : 여러 개 추가
nums = [1, 2, 3]
nums.extend([4, 5, 6])
print(nums)

[1, 2, 3, 4, 5, 6]


In [46]:
# remove() : 값으로 삭제
fruits = ["apple", "banana", "orange"]
fruits.remove("banana")
print(fruits)

# 수정은 인덱스 할당, 슬라이싱 할당으로 수정

['apple', 'orange']


In [47]:
# pop() : 인덱스로 삭제 후 반환
nums = [10, 20, 30]
result = nums.pop() # 마지막 인덱스 삭제 후 반환
print(result)
print(nums)

nums = [10, 20, 30]
result = nums.pop(1) # 인덱스1 삭제 후 반환
print(result)
print(nums)

30
[10, 20]
20
[10, 30]


In [1]:
# clear() : 전체 삭제
nums = [10, 20, 30]
nums.clear()
print(nums)

[]


In [2]:
# del 문
nums = [10, 20, 30, 40]
del nums[1]
print(nums)

[10, 30, 40]


In [3]:
# reverse() : 순서 뒤집기, 정렬과 상관없이 현재 순서를 거꾸로 만든다.
nums = [10, 20, 30, 40]
nums.reverse()
print(nums)

[40, 30, 20, 10]


In [4]:
# count() : 특정 값이 몇개인지
nums = [10, 20, 10, 30, 10]
print(nums.count(10)) # 3


3


In [5]:
# index() : 특정 값의 인덱스
fruits = ["apple", "banana", "orange"]
print(fruits.index("banana")) # 1

1


In [6]:
# 정렬 메서드
nums = [50, 10, 40, 20]
nums.sort() # 오름차순
print(nums)

nums = [50, 10, 40, 20]
nums.sort(reverse=True) # 내림차순
print(nums)

[10, 20, 40, 50]
[50, 40, 20, 10]


In [7]:
nums = [50, 10, 40, 20]
result = sorted(nums)
print(nums)
print(result)

nums = [50, 10, 40, 20]
result = sorted(nums, reverse=True)
print(result)

fruits = ["banana", "apple", "orange"]
result = sorted(fruits)
print(result)

# key매갲변수를 이용하여 문자열 길이로 정렬
fruits = ["watermelon", "kiwi", "banana", "apple"]
result = sorted(fruits, key=len)
print(result)

# 매개변수 key값으로는 함수가 온다. 뒤에서 람다함수를 배우면
# key값으로 람다식을 대입하여 다양한 요구 사항의 정렬도 가능하다.
# 자기 자신을 정렬할때는 sort()메서드, 다양한 형태의 정렬된 리스트를 반환할때는 sorted() 내장함수 사용

[50, 10, 40, 20]
[10, 20, 40, 50]
[50, 40, 20, 10]
['apple', 'banana', 'orange']
['kiwi', 'apple', 'banana', 'watermelon']
